### ISSUE TITLE
Replace existing workspace

### ISSUE THREAD

**Issue by AQLT** [rjdverse/rjd3workspace#1]
It didn't manage to replace an existing workspace, does the parameter `failIfExists` works (https://github.com/jdemetra/jdplus-main/blob/b0725dd5e921d83f2c9e3a3e6b881ea6d7546810/jdplus-main-base/jdplus-sa-base-parent/jdplus-sa-base-workspace/src/main/java/jdplus/sa/base/workspace/Ws.java#L93)?

``` r
library(rjdemetra3)
dir <- tempdir()
wk <- .jws_new()
save_workspace(wk, file.path(dir, "workspace.xml"))
#> [1] TRUE
save_workspace(wk, file.path(dir, "workspace.xml"), replace = TRUE)
#> [1] FALSE
save_workspace(wk, file.path(dir, "workspace.xml"), replace = FALSE)
#> [1] FALSE
```

**Comment by TanguyBarthelemy** [comment]
This problem is still unresolved but it's a major issue in creating workspaces.

**Comment by TanguyBarthelemy** [comment]
@immurb and @palatej
