### ISSUE TITLE
set_specification doesn't seem to work

### ISSUE THREAD

**Issue by carlos-saez** [rjdverse/rjd3workspace#41]
I was testing the functions in this package and I have a problem with set_specification. When I try to use it to change the specification of some sa item in a workspace I get an error. The following code reproduces the error:
```
# Create a workspace
jws <- rjdemetra3::.jws_new()
jsap <- rjdemetra3::.jws_sap_new(jws, "jsap1")

# Add a series
ts <- rjd3toolkit::Imports$Spain
rsafull <- rjd3tramoseats::tramoseats_spec("rsafull")
rjdemetra3::add_sa_item(jsap, "sa", x = ts, spec = rsafull)

rjdemetra3::.jws_compute(jws)

# Change specification
newspec <- rjd3tramoseats::tramoseats_spec("rsa0")
rjdemetra3::set_specification(jsap, 1, newspec)    # ERROR!
```
The error I get when executing the last line is;
```
Error en .jcall(jsap, "V", "setSpecification", as.integer(idx - 1), jspec): 
  method setSpecification with signature (ILjdplus/sa/base/api/SaSpecification;)V not found
```
I don't know if it's really a bug or I'm using the function in a wrong way. In the second case, I would appreciate some indications on how to use it properly.

**Comment by annasmyk** [comment]
Hi Carlos

did you try with the last version of rjd3 workspace ?
anna

**Comment by carlos-saez** [comment]
Hi Anna,

I've tried it now but I get the same error.

Carlos

**Comment by TanguyBarthelemy** [comment]
Hi Carlos,
That's a Java issue, I'll take a look and get back to you before end of june.

**Comment by TanguyBarthelemy** [comment]
Thank you @AQLT for this issue!
